'use client';

import React, { useState } from 'react';
import jsPDF from 'jspdf';
import {
  scenarios,
  calculateAssessment,
  getJFCLabel,
  type AssessmentResult,
  type Scenario
} from '@/lib/assessmentScoring';
import './AssessmentForm.css';
import './AssessmentResults.css';

interface ScenarioAssessmentProps {
  lang?: 'en' | 'ja';
}

const ScenarioAssessment: React.FC<ScenarioAssessmentProps> = ({ lang = 'en' }) => {
  const [currentScenario, setCurrentScenario] = useState(0);
  const [responses, setResponses] = useState<Record<string, string>>({});
  const [result, setResult] = useState<AssessmentResult | null>(null);

  const handleOptionSelect = (scenarioId: string, optionId: string) => {
    setResponses(prev => ({ ...prev, [scenarioId]: optionId }));
  };

  const handleNext = () => {
    if (currentScenario < scenarios.length - 1) {
      setCurrentScenario(prev => prev + 1);
    } else {
      const assessmentResult = calculateAssessment(responses);
      setResult(assessmentResult);
    }
  };

  const handlePrev = () => {
    if (currentScenario > 0) {
      setCurrentScenario(prev => prev - 1);
    }
  };

  const handleReset = () => {
    setResponses({});
    setCurrentScenario(0);
    setResult(null);
  };

  const scenario = scenarios[currentScenario];
  const isOptionSelected = responses[scenario.id] !== undefined;

  const generatePDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(24);
    doc.setTextColor(26, 26, 26);
    doc.text('SOLUNAI', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Japanese Fit Coefficient (JFC) Assessment Report', pageWidth / 2, 28, { align: 'center' });

    // SCE Badge
    doc.setFontSize(8);
    doc.setTextColor(0, 122, 255);
    doc.text('Powered by Solunai Continuity Engine', pageWidth / 2, 35, { align: 'center' });

    // JFC Score
    doc.setFontSize(16);
    doc.setTextColor(26, 26, 26);
    doc.text('Japanese Fit Coefficient (JFC)', pageWidth / 2, 50, { align: 'center' });

    doc.setFontSize(36);
    doc.setTextColor(0, 122, 255);
    doc.text(`${result.jfc}%`, pageWidth / 2, 65, { align: 'center' });

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(getJFCLabel(result.jfc), pageWidth / 2, 73, { align: 'center' });

    // Consistency Index
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(`Consistency Index: ${result.consistencyIndex}%`, pageWidth / 2, 80, { align: 'center' });

    // Dimension Scores
    doc.setFontSize(14);
    doc.setTextColor(26, 26, 26);
    doc.text('Dimension Breakdown', 20, 95);

    doc.setFontSize(10);
    let yPos = 105;

    const dimensionLabels: Record<string, string> = {
      WA: 'Harmony (Wa)',
      LOYALTY: 'Long-term Commitment',
      COMM: 'Communication Style',
      TEAM: 'Team Integration',
      HIER: 'Hierarchy Respect'
    };

    for (const [key, label] of Object.entries(dimensionLabels)) {
      doc.setTextColor(26, 26, 26);
      doc.text(`${label}:`, 20, yPos);
      doc.setTextColor(0, 122, 255);
      doc.text(`${result.normalizedScores[key as keyof typeof result.normalizedScores]}%`, 100, yPos);
      yPos += 8;
    }

    // Risk Flags
    if (result.riskFlags.length > 0) {
      yPos += 5;
      doc.setFontSize(12);
      doc.setTextColor(26, 26, 26);
      doc.text('Risk Areas', 20, yPos);
      yPos += 8;

      doc.setFontSize(9);
      result.riskFlags.forEach(flag => {
        const color = flag.level === 'critical' ? [220, 38, 38] : [234, 179, 8];
        doc.setTextColor(color[0], color[1], color[2]);
        const symbol = flag.level === 'critical' ? '[!]' : '[*]';
        doc.text(`${symbol} ${flag.message}`, 20, yPos);
        yPos += 6;
      });
    }

    // Strengths
    if (result.strengths.length > 0) {
      yPos += 5;
      doc.setFontSize(12);
      doc.setTextColor(26, 26, 26);
      doc.text('Strengths', 20, yPos);
      yPos += 8;

      doc.setFontSize(9);
      doc.setTextColor(22, 163, 74);
      result.strengths.forEach(strength => {
        doc.text(`+ ${strength}`, 20, yPos);
        yPos += 6;
      });
    }

    // Management Style
    yPos += 5;
    doc.setFontSize(12);
    doc.setTextColor(26, 26, 26);
    doc.text('Recommended Management Style', 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const splitStyle = doc.splitTextToSize(result.managementStyle, 170);
    doc.text(splitStyle, 20, yPos);

    // Footer
    yPos = 270;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('This report was generated by the Solunai Continuity Engine (SCE)', pageWidth / 2, yPos, { align: 'center' });
    doc.text(`Assessment Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPos + 5, { align: 'center' });
    doc.text('www.solunai.co.jp', pageWidth / 2, yPos + 10, { align: 'center' });

    doc.save('Solunai_JFC_Assessment_Report.pdf');
  };

  // Render results
  if (result) {
    return (
      <section className="assessment-results-section">
        <div className="results-container">
          <div className="results-header">
            <div className="sce-badge">SCE ANALYSIS COMPLETE</div>
            <h2 className="results-title">Japanese Fit Coefficient (JFC)</h2>
            <p className="results-subtitle">
              Powered by Solunai Continuity Engine - 14 Scenario SJT Analysis
            </p>
          </div>

          <div className="overall-score-card">
            <div className={`score-circle ${result.jfc >= 65 ? 'excellent' : result.jfc >= 50 ? 'good' : result.jfc >= 35 ? 'moderate' : 'developing'}`}>
              <span className="score-value">{result.jfc}%</span>
            </div>
            <div className="score-info">
              <h3 className="score-label">{getJFCLabel(result.jfc)}</h3>
              <p className="score-description">
                Consistency Index: {result.consistencyIndex}%
              </p>
            </div>
          </div>

          <div className="category-scores">
            <div className="category-card">
              <h4 className="category-name">Harmony (Wa)</h4>
              <div className="category-bar">
                <div
                  className={`bar-fill ${result.normalizedScores.WA >= 70 ? 'excellent' : result.normalizedScores.WA >= 50 ? 'good' : 'moderate'}`}
                  style={{ width: `${result.normalizedScores.WA}%` }}
                />
              </div>
              <span className="category-score">{result.normalizedScores.WA}%</span>
            </div>

            <div className="category-card">
              <h4 className="category-name">Long-term Commitment</h4>
              <div className="category-bar">
                <div
                  className={`bar-fill ${result.normalizedScores.LOYALTY >= 70 ? 'excellent' : result.normalizedScores.LOYALTY >= 50 ? 'good' : 'moderate'}`}
                  style={{ width: `${result.normalizedScores.LOYALTY}%` }}
                />
              </div>
              <span className="category-score">{result.normalizedScores.LOYALTY}%</span>
            </div>

            <div className="category-card">
              <h4 className="category-name">Communication Style</h4>
              <div className="category-bar">
                <div
                  className={`bar-fill ${result.normalizedScores.COMM >= 70 ? 'excellent' : result.normalizedScores.COMM >= 50 ? 'good' : 'moderate'}`}
                  style={{ width: `${result.normalizedScores.COMM}%` }}
                />
              </div>
              <span className="category-score">{result.normalizedScores.COMM}%</span>
            </div>

            <div className="category-card">
              <h4 className="category-name">Team Integration</h4>
              <div className="category-bar">
                <div
                  className={`bar-fill ${result.normalizedScores.TEAM >= 70 ? 'excellent' : result.normalizedScores.TEAM >= 50 ? 'good' : 'moderate'}`}
                  style={{ width: `${result.normalizedScores.TEAM}%` }}
                />
              </div>
              <span className="category-score">{result.normalizedScores.TEAM}%</span>
            </div>

            <div className="category-card">
              <h4 className="category-name">Hierarchy Respect</h4>
              <div className="category-bar">
                <div
                  className={`bar-fill ${result.normalizedScores.HIER >= 70 ? 'excellent' : result.normalizedScores.HIER >= 50 ? 'good' : 'moderate'}`}
                  style={{ width: `${result.normalizedScores.HIER}%` }}
                />
              </div>
              <span className="category-score">{result.normalizedScores.HIER}%</span>
            </div>
          </div>

          {result.riskFlags.length > 0 && (
            <div className="results-insights">
              <h3 className="insights-title">Risk Areas</h3>
              <div className="insights-grid">
                {result.riskFlags.map((flag, i) => (
                  <div key={i} className={`insight-card ${flag.level === 'critical' ? 'growth' : 'growth'}`}>
                    <span className="insight-icon">{flag.level === 'critical' ? '!' : '*'}</span>
                    <p>{flag.message}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {result.strengths.length > 0 && (
            <div className="results-insights">
              <h3 className="insights-title">Strengths</h3>
              <div className="insights-grid">
                {result.strengths.map((strength, i) => (
                  <div key={i} className="insight-card strength">
                    <span className="insight-icon">+</span>
                    <p>{strength}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {result.developmentAreas.length > 0 && (
            <div className="results-insights">
              <h3 className="insights-title">Development Areas</h3>
              <div className="insights-grid">
                {result.developmentAreas.map((area, i) => (
                  <div key={i} className="insight-card growth">
                    <span className="insight-icon">*</span>
                    <p>{area}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="sce-memory-note">
            <div className="memory-icon">MGT</div>
            <p>
              <strong>Management Recommendation:</strong> {result.managementStyle}
            </p>
          </div>

          {result.culturalStressPoints.length > 0 && (
            <div className="sce-memory-note">
              <div className="memory-icon">CSP</div>
              <p>
                <strong>Cultural Stress Points:</strong> {result.culturalStressPoints.join('; ')}
              </p>
            </div>
          )}

          <div className="results-actions">
            <button className="action-button primary" onClick={generatePDF}>
              Download Full Report (PDF)
            </button>
            <button className="action-button secondary" onClick={handleReset}>
              Take Assessment Again
            </button>
          </div>
        </div>
      </section>
    );
  }

  // Render assessment form
  return (
    <section className="assessment-form-section">
      <div className="assessment-form-container">
        <div className="form-progress">
          <div className="progress-bar">
            <div
              className="progress-fill"
              style={{ width: `${((currentScenario + 1) / scenarios.length) * 100}%` }}
            />
          </div>
          <span className="progress-text">
            Scenario {currentScenario + 1} of {scenarios.length}
          </span>
        </div>

        <div className="questions-container">
          <div className="question-card scenario-card">
            <h3 className="question-label">{lang === 'ja' ? scenario.titleJA : scenario.title}</h3>
            <p className="scenario-context">{lang === 'ja' ? scenario.contextJA : scenario.context}</p>

            <div className="scenario-options">
              {scenario.options.map((option) => (
                <button
                  key={option.id}
                  className={`scenario-option ${responses[scenario.id] === option.id ? 'selected' : ''}`}
                  onClick={() => handleOptionSelect(scenario.id, option.id)}
                >
                  <span className="option-letter">{option.id.slice(-1)}</span>
                  <span className="option-text">{lang === 'ja' ? option.textJA : option.text}</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="form-navigation">
          <button
            className="nav-button prev"
            onClick={handlePrev}
            disabled={currentScenario === 0}
          >
            Previous
          </button>
          <button
            className="nav-button next"
            onClick={handleNext}
            disabled={!isOptionSelected}
          >
            {currentScenario === scenarios.length - 1 ? 'Complete' : 'Next'}
          </button>
        </div>
      </div>
    </section>
  );
};

export default ScenarioAssessment;
